# Generated by Django 5.2.1 on 2025-05-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='page_size',
            field=models.PositiveIntegerField(default=200, verbose_name='Укажите кол-во страниц'),
        ),
    ]
