# Generated by Django 5.2.1 on 2025-05-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_page_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='page_size',
        ),
        migrations.AddField(
            model_name='film',
            name='page_number',
            field=models.PositiveIntegerField(default=200, null=True, verbose_name='Укажите кол-во страниц'),
        ),
    ]
