# Generated by Django 5.2.1 on 2025-05-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_remove_film_page_size_film_page_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
