# Generated by Django 5.2.1 on 2025-05-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_film_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='page_number',
        ),
    ]
