# Generated by Django 5.2.1 on 2025-05-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
